import { ContactForm } from "@/components/contact-form";
import { FaqList } from "@/components/faq-list";
import { FormatsDressCode } from "@/components/formats-dress-code";
import { GatheringSplit } from "@/components/gathering-split";
import { HeroIntro } from "@/components/hero-intro";
import { MethodTimeline } from "@/components/method-timeline";
import { Photo } from "@/components/photo";
import { SiteFooter } from "@/components/site-footer";
import { SaveSince } from "@/components/save-since";
import type { Dictionary } from "@/lib/dictionaries";
import { chapterPhotos, photos } from "@/lib/photos";
import { brand, type Locale } from "@/lib/site";
import { ui } from "@/lib/ui";

const stats = {
  pt: [["20+", "Anos de experiência"], ["3", "Idiomas"], ["1", "Equipe local"], ["2013", "Marco nacional"], ["1", "Caso de cada vez"]],
  en: [["20+", "Years of experience"], ["3", "Languages"], ["1", "Local team"], ["2013", "National milestone"], ["1", "One case at a time"]],
  es: [["20+", "Años de experiencia"], ["3", "Idiomas"], ["1", "Equipo local"], ["2013", "Hito nacional"], ["1", "Un caso a la vez"]],
} as const;

const home = {
  pt: { hero: "Casamento civil no Brasil para casais homoafetivos estrangeiros, com orientação sobre o processo, coordenação local e a possibilidade de celebrar esse momento no Rio de Janeiro.", presentationTitle: "O casamento de vocês pode acontecer legalmente aqui.", p1: "No Brasil, o casamento civil entre pessoas do mesmo sexo é reconhecido. Para casais estrangeiros, o processo começa com a análise da nacionalidade, do estado civil e dos documentos disponíveis.", p2: "Nossa equipe organiza as etapas no Brasil e coordena o contato com cartório, tradução juramentada e suporte jurídico especializado, quando necessário.", note: "Cada caso é analisado individualmente. Os documentos, requisitos e prazos variam conforme o casal e o cartório responsável.", destination: "Para muitos casais, vir ao Brasil representa a possibilidade do casamento civil. O Rio transforma essa conquista em uma experiência para ser vivida e lembrada.", travelTitle: "Vocês planejam de onde estiverem. Nossa equipe cuida do Brasil.", travel: [["Análise à distância", "A primeira conversa e a análise inicial podem acontecer online, antes de qualquer viagem ou contratação local."], ["Coordenação no Brasil", "Mantemos contato com cartório, tradutores e profissionais envolvidos no processo brasileiro."], ["Viagem e celebração", "Quando o casal também deseja celebrar, organizamos hospedagem, transporte, cerimônia, fotografia e experiências no Rio."]], about: ["Aqui, a história de vocês é recebida com respeito.", "Vocês não precisam explicar por que esse casamento importa.", "Eu também sou gay e sei o que significa poder viver esse momento com liberdade. Meu trabalho é receber a história de vocês com respeito e transformar o processo brasileiro em um caminho claro, humano e bem conduzido.", "Desde 2004, eu e minha equipe realizamos eventos e casamentos no Rio de Janeiro. Hoje, usamos essa experiência para receber casais do Brasil e do mundo."], emotional: "A celebração pode ser íntima, apenas para o casal, ou incluir as pessoas que fizeram parte dessa história.", contact: ["Contem um pouco sobre vocês.", "Para orientar o primeiro passo, precisamos entender onde vocês vivem, a nacionalidade e o estado civil de cada pessoa, os documentos disponíveis e quando imaginam vir ao Brasil.", "Esta conversa inicial também ajuda a identificar se vocês desejam apenas o casamento civil ou uma experiência completa no Rio."], faq: ["Antes de começar", "As primeiras respostas sobre o casamento civil de casais homoafetivos estrangeiros no Brasil."] },
  en: { hero: "Civil wedding in Brazil for foreign same-sex couples, with guidance through the process, local coordination and the possibility of celebrating this moment in Rio de Janeiro.", presentationTitle: "Your wedding can legally happen here.", p1: "In Brazil, civil marriage between people of the same sex is recognized. For foreign couples, the process begins with an analysis of nationality, marital status and available documents.", p2: "Our team organizes the steps in Brazil and coordinates contact with the registry office, sworn translation and specialized legal support when necessary.", note: "Each case is assessed individually. Documents, requirements and timelines vary according to the couple and the responsible registry office.", destination: "For many couples, coming to Brazil represents the possibility of a civil wedding. Rio turns that achievement into an experience to live and remember.", travelTitle: "You plan from wherever you are. Our team takes care of Brazil.", travel: [["Remote analysis", "The first conversation and initial analysis can happen online, before any trip or local booking."], ["Coordination in Brazil", "We stay in contact with the registry office, translators and professionals involved in the Brazilian process."], ["Travel and celebration", "When the couple also wishes to celebrate, we organize accommodation, transportation, ceremony, photography and experiences in Rio."]], about: ["Here, your story is received with respect.", "You do not need to explain why this wedding matters.", "I am gay too, and I know what it means to be able to live this moment freely. My work is to receive your story with respect and turn the Brazilian process into a clear, human and well-conducted path.", "Since 2004, my team and I have produced events and weddings in Rio de Janeiro. Today, we use this experience to welcome couples from Brazil and around the world."], emotional: "The celebration can be intimate, just for the couple, or include the people who have been part of this story.", contact: ["Tell us a little about yourselves.", "To guide the first step, we need to understand where you live, each person's nationality and marital status, the documents available and when you imagine coming to Brazil.", "This initial conversation also helps identify whether you want only the civil wedding or a complete experience in Rio."], faq: ["Before you begin", "First answers about civil marriage for foreign same-sex couples in Brazil."] },
  es: { hero: "Matrimonio civil en Brasil para parejas extranjeras del mismo sexo, con orientación sobre el proceso, coordinación local y la posibilidad de celebrar este momento en Río de Janeiro.", presentationTitle: "Su boda puede celebrarse legalmente aquí.", p1: "En Brasil, el matrimonio civil entre personas del mismo sexo está reconocido. Para las parejas extranjeras, el proceso comienza con el análisis de la nacionalidad, el estado civil y los documentos disponibles.", p2: "Nuestro equipo organiza las etapas en Brasil y coordina el contacto con el registro civil, la traducción jurada y el apoyo jurídico especializado cuando sea necesario.", note: "Cada caso se analiza individualmente. Los documentos, requisitos y plazos varían según la pareja y el registro civil responsable.", destination: "Para muchas parejas, venir a Brasil representa la posibilidad del matrimonio civil. Río transforma este logro en una experiencia para vivir y recordar.", travelTitle: "Ustedes planifican desde donde estén. Nuestro equipo se ocupa de Brasil.", travel: [["Análisis a distancia", "La primera conversación y el análisis inicial pueden realizarse online, antes de cualquier viaje o contratación local."], ["Coordinación en Brasil", "Mantenemos el contacto con el registro civil, traductores y profesionales involucrados en el proceso brasileño."], ["Viaje y celebración", "Cuando la pareja también desea celebrar, organizamos alojamiento, transporte, ceremonia, fotografía y experiencias en Río."]], about: ["Aquí, la historia de ustedes es recibida con respeto.", "No necesitan explicar por qué este matrimonio importa.", "Yo también soy gay y sé lo que significa poder vivir este momento con libertad. Mi trabajo es recibir la historia de ustedes con respeto y transformar el proceso brasileño en un camino claro, humano y bien conducido.", "Desde 2004, mi equipo y yo realizamos eventos y bodas en Río de Janeiro. Hoy, usamos esta experiencia para recibir parejas de Brasil y de todo el mundo."], emotional: "La celebración puede ser íntima, solo para la pareja, o incluir a las personas que formaron parte de esta historia.", contact: ["Cuéntennos un poco sobre ustedes.", "Para orientar el primer paso, necesitamos entender dónde viven, la nacionalidad y el estado civil de cada persona, los documentos disponibles y cuándo imaginan venir a Brasil.", "Esta conversación inicial también ayuda a identificar si desean solamente el matrimonio civil o una experiencia completa en Río."], faq: ["Antes de empezar", "Las primeras respuestas sobre el matrimonio civil de parejas extranjeras del mismo sexo en Brasil."] },
} as const;

export function WeddedHome({ locale, dict }: { locale: Locale; dict: Dictionary }) {
  const copy = ui[locale];
  const text = home[locale];
  const chapters = copy.chapters;
  const section = (id: string, children: React.ReactNode, className = "") => <section id={id} className={`scroll-mt-24 ${className}`}>{children}</section>;
  return <div className="bg-white text-wine"><HeroIntro src={photos.hero} kicker="RIO DE JANEIRO · BRASIL" name="Legal Gay Wedding Brazil" lead={text.hero} cta={dict.hero.cta} />
    <div className="site-shell mx-auto bg-cream"><section className="grid grid-cols-2 border-y border-wine/10 bg-cream md:grid-cols-5">{stats[locale].map(([number, label]) => <div key={label} className="border-wine/10 px-4 py-7 text-center last:col-span-2 md:border-r md:last:col-span-1"><strong className="block font-display text-3xl">{number}</strong><span className="mt-1 block text-[0.68rem] tracking-[0.12em] text-wine/65 uppercase">{label}</span></div>)}</section>
      {section("civil", <div className="px-6 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-[720px] text-center"><p className="text-[0.72rem] tracking-[0.18em] uppercase">{dict.editorial.subtitle}</p><h2 className="mt-4 font-display text-4xl md:text-6xl">{text.presentationTitle}</h2><p className="mt-7 leading-8 text-wine/75">{text.p1}</p><p className="mt-4 leading-8 text-wine/75">{text.p2}</p><p className="mt-6 text-sm leading-7 text-wine/60">{text.note}</p></div></div>)}
      <MethodTimeline kicker="O caminho" title="Do primeiro contato ao casamento civil." lead="" steps={chapters} photos={chapterPhotos} />
      {section("destination", <div className="bg-cream px-6 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-[720px] text-center"><p className="text-[0.72rem] tracking-[0.18em] uppercase">Rio de Janeiro</p><h2 className="mt-4 font-display text-4xl md:text-6xl">Casar no Brasil. Celebrar no Rio.</h2><p className="mt-6 leading-8 text-wine/75">{text.destination}</p><a href="#formats" className="btn-wine mt-8 inline-flex">Conhecer as possibilidades</a></div></div>)}
      {section("international", <div className="px-6 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-[1100px]"><p className="text-[0.72rem] tracking-[0.18em] uppercase">Para casais que vivem no exterior</p><h2 className="mt-4 max-w-3xl font-display text-4xl md:text-6xl">{text.travelTitle}</h2><div className="mt-12 grid gap-8 md:grid-cols-3">{text.travel.map(([title, body]) => <div key={title} className="border-t border-wine/15 pt-5"><h3 className="font-display text-3xl">{title}</h3><p className="mt-4 leading-8 text-wine/75">{body}</p></div>)}</div></div></div>)}
      <section id="formats"><FormatsDressCode kicker="Formas de viver esse momento" title="Do processo legal à celebração no Rio." lead="" packATitle="Legal Gay Wedding Brazil" packABody={dict.venuesHome.cards.xian.text} packBTitle="Legal Wedding + Rio Experience" packBBody={dict.venuesHome.cards["cristo-redentor"].text} /></section>
      <GatheringSplit caption={text.about[0]} kicker="Quem estará com vocês" title={text.about[1]} body={`${text.about[2]} ${text.about[3]}`} meta={[{label:"Desde:",value:"2004"},{label:"Idiomas:",value:"PT · EN · ES"},{label:"Base:",value:"Rio de Janeiro"}]} photo={photos.dinner} />
      <section id="details"><FormatsDressCode kicker="Como trabalhamos" title={dict.method.title} lead="" packATitle="Legal Gay Wedding Brazil" packABody={dict.packABody} packBTitle="Legal Wedding + Rio Experience" packBBody={dict.packBBody} /></section>
      <section className="bg-cream px-6 py-20 text-center md:px-10 md:py-28"><p className="mx-auto max-w-2xl text-lg leading-8 text-wine/75">{text.emotional}</p><p className="mt-8 text-xs tracking-[0.16em]">CASAMENTO CIVIL · ELOPEMENT WEDDING<br />RIO DE JANEIRO · DESTINATION WEDDING</p></section>
      <section id="rsvp" className="grid md:grid-cols-2"><Photo src={photos.vows} alt="" className="min-h-[70vh]" sizes="50vw" /><div className="flex items-center px-6 py-16 md:px-12"><div className="w-full max-w-md"><p className="text-[0.72rem] tracking-[0.18em] uppercase">Análise inicial</p><h2 className="mt-3 font-display text-4xl md:text-5xl">{text.contact[0]}</h2><p className="mt-5 leading-8 text-wine/75">{text.contact[1]}</p><p className="mt-4 leading-8 text-wine/75">{text.contact[2]}</p><div className="mt-6 flex flex-col gap-2 text-sm"><a href={`mailto:${brand.email}`} className="underline">{brand.email}</a><a href={`https://wa.me/${brand.whatsapp}`} className="underline">{brand.whatsappDisplay}</a></div><div className="mt-10"><ContactForm dict={dict} /></div></div></div></section>
      <section id="faq" className="bg-cream px-6 py-24 md:px-10 md:py-32"><div className="mx-auto grid max-w-[1100px] gap-12 md:grid-cols-2"><div><h2 className="font-display text-4xl md:text-6xl">{text.faq[0]}</h2><p className="mt-6 leading-8 text-wine/75">{text.faq[1]}</p></div><FaqList items={dict.faq.items} /></div></section><SiteFooter locale={locale} dict={dict} /></div></div>;
}

function unusedSaveSince({ copy, body }: { copy: typeof ui.pt; body: string }) { return <SaveSince copy={copy} body={body} />; }
